### ISSUE TITLE
Fazer busca dinâmica

### ISSUE THREAD

**Issue by lucaspineda** [thiagodosanjos31/Acompanhamento-de-orcamento#1]
Seria interessante fazer com que a busca fosse dinâmica, conforme o usuário ir digitando os elementos devem ir aparecendo na tela, sem a necessidade de clicar no botão de pesquisa.

Página: consulta.html
![image](https://user-images.githubusercontent.com/25157126/58433436-b102b700-808d-11e9-98b2-091cf7eb565e.png)

**Comment by thiagodosanjos31** [comment]
Obrigado pela sugestão Lucas.


Realizei um novo upload dos arquivos com a busca dinâmica já implementada. Agora você pode comparar como era e como ficou com a nova customização.
